### ISSUE TITLE
Documentation request: how to make a custom IAM role for Cloud Run with the most restrictive permissions

### ISSUE THREAD

**Issue by simonw** [GoogleCloudPlatform/github-actions#92]
Quoting https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/README.md

https://github.com/GoogleCloudPlatform/github-actions/blob/20c294aabd5331f9f7b8a26e6075d41c31ce5e0d/example-workflows/cloud-run/README.md#L61-L64

I have tried and failed to figure out how to do this. Official documentation on how to create an IAM role with the most restrictive permissions possible to deploy to Cloud Run (or ideally a specific service on Cloud Run) would be _incredibly_ useful.

**Comment by sethvargo** [comment]
Does [this documentation](https://cloud.google.com/iam/docs/creating-custom-roles) help? Or are you looking for the exact set of permissions?

**Comment by simonw** [comment]
I need the exact set of permissions - ideally with an extremely detailed set of step-by-step instructions for applying them.

Every time I've tried to figure this out on my own I have got frustrated and given up!

**Comment by simonw** [comment]
I spotted another example of this today!

https://cloud.google.com/vision/docs/quickstart-client-libraries

<img width="865" alt="Quickstart__Using_Client_Libraries_ _ _Cloud_Vision_API_ _ _Google_Cloud" src="https://user-images.githubusercontent.com/9599/80518330-2e3c4900-893b-11ea-8f0c-10527ffcb570.png">

So maybe what I'm looking for here is a Google-wide documentation policy that no-one is ever allowed to write the equivalent of "figuring out the correct permissions for using this feature is an exercise left for the reader".

**Comment by simonw** [comment]
Linking to https://cloud.google.com/iam/docs/creating-custom-roles doesn't help because the hard part is figuring out _which_ permissions to assign to the role.

**Comment by sethvargo** [comment]
To build the container with Cloud Build, you must have the following permissions at the project level (there's a catch, see <sup>1</sup> below):

```text
cloudbuild.builds.create
cloudbuild.builds.get
cloudbuild.builds.list
```



iam.serviceAccounts.actAs
run.services.create
run.services.getIamPolicy
run.services.setIamPolicy
run.services.update
storage.buckets.get
storage.buckets.list
storage.objects.create
storage.objects.get
storage.objects.list

<sup>1</sup> Cloud Build logs are, by default, stored in a bucket that you don't manage. If you want to keep the default behavior, you have to grant the Project Viewer role to your service account. Note, it's not because of any of the permissions on Project Viewer, but rather because Project Viewer is included in the default legacy ACLs for buckets ([more here](https://github.com/GoogleCloudPlatform/cloud-builders/issues/120)). Alternatively, you can create your own bucket for logs, and specify the [`logBucket`](https://cloud.google.com/cloud-build/docs/build-config#logsbucket) configuration or CLI option. If you choose to make your own bucket, the service account requires `storage.objects.*` on the bucket.

**Comment by sethvargo** [comment]
To build the container with Cloud Build, you must have the following permissions at the project level<sup>1</sup>:

```text
cloudbuild.builds.create
cloudbuild.builds.get
cloudbuild.builds.list
remotebuildexecution.blobs.get
storage.buckets.get
storage.buckets.list
storage.objects.create
storage.objects.get
storage.objects.list
```

To deploy the service to Cloud Run, grant the following permissions at the project level:

```text
iam.serviceAccounts.actAs
run.services.create
run.services.update
```

To make the Cloud Run service public, grant the following permissions at the project level:

```text
run.services.getIamPolicy
run.services.setIamPolicy
```

<sup>1</sup> Cloud Build logs are, by default, stored in a bucket that you don't manage. If you want to keep the default behavior, you have to grant the Project Viewer role to your service account. Note, it's not because of any of the permissions on Project Viewer, but rather because Project Viewer is included in the default legacy ACLs for buckets ([more here](https://github.com/GoogleCloudPlatform/cloud-builders/issues/120)). Alternatively, you can create your own bucket for logs, and specify the [`logBucket`](https://cloud.google.com/cloud-build/docs/build-config#logsbucket) configuration or CLI option. If you choose to make your own bucket, the service account requires `storage.objects.*` on the bucket.

Also note that permissions can be even-more finer-grained by creating some of these resources in advance. Then, instead of applying at the project level, you apply at the resource level. However, this creates a chicken-and-egg problem where the resource has to exist before you can grant a service account permissions on it.

**Comment by sethvargo** [comment]
> I need the exact set of permissions - ideally with an extremely detailed set of step-by-step instructions for applying them.

I listed the set of permissions above. I also tested and verified it's working with the Cloud Run sample in this repo. IMO, the easiest way to curate custom roles is via the Web UI (IAM > Roles > Create), but you can also do it via the API.

<img width="604" alt="Screen Shot 2020-04-28 at 8 22 45 PM" src="https://user-images.githubusercontent.com/408570/80550433-1a6e0280-898e-11ea-8fc5-890d12bc553f.png">

<img width="696" alt="Screen Shot 2020-04-28 at 8 23 00 PM" src="https://user-images.githubusercontent.com/408570/80550435-1c37c600-898e-11ea-8b82-c9ce554166d7.png">

> So maybe what I'm looking for here is a Google-wide documentation policy that no-one is ever allowed to write the equivalent of "figuring out the correct permissions for using this feature is an exercise left for the reader".

Most of the time, these are left as an exercise to the reader because each use case is different. The collection of required permissions varies greatly by intended use case. As a concrete example, take this example workflow. If you run `gcloud builds submit` with the `--async` flag, gcloud won't stream logs. If gcloud doesn't need to stream logs, then the service account doesn't need permission on Cloud Storage.

We have no way of knowing exactly how a user plans to interact with a service, so it's not as simple as "here's the list". This is why each service lists all its IAM roles and permissions in their respective documentation.

Finally, I'd like to remind you that this repo, like everything under GoogleCloudPlatform/*, is subject to our code of conduct. Our Tech Writers work very hard to bring users the best possible documentation, and attacking their work on here or [on social media](https://twitter.com/simonw/status/1255179302640824320) is disrespectful. I understand that you're frustrated, but remember that there are humans on the other side of those keyboards.

**Comment by simonw** [comment]
Thanks @sethvargo - this is exactly the information I was looking for, and if anything it's more comprehensive than I needed! You've answered my query perfectly.

My aim with that tweet wasn't to criticize the documentation authors so much as it was to highlight my continued frustrations with how hard it is to figure out the safe way to work with IAM privileges.

I handled that badly. My tone was snarky and rude, and you're right to describe it as disrespectful.

I apologise to the people who I disrespected, and I'll aim to do better in the future.

**Comment by MunGell** [comment]
Hi @sethvargo,

I am stuck with the same problem and found your reply very useful.

However, it looks like permissions of the custom role are not enough to get access to `https://storage.googleapis.com/123455667899.cloudbuild-logs.googleusercontent.com/log-7a3eeb61-5371-4148-8c55-a1c7d4c8799d.txt` bucket to allow for log streaming. 

<img width="404" alt="Screen Shot 2020-06-29 at 22 14 54" src="https://user-images.githubusercontent.com/812976/86056827-f8f4ca00-ba55-11ea-91aa-429076e66eb6.png">

Would setting custom `--gcs-log-dir` be the only option in this case?

**Comment by sethvargo** [comment]
Correct. You either need to grant Project Viewer or use a custom bucket.

**Comment by MunGell** [comment]
Thanks for the quick reply
