### ISSUE TITLE
setup-gcloud: authentication fields description is misleading

### ISSUE THREAD

**Issue by IlyaSemenov** [GoogleCloudPlatform/github-actions#95]
### TL;DR
The documentation for setup-gcloud description is misleading:

> If `service_account_key` is specified, authenticates the gcloud CLI tool
    using the inputs: `service_account_email` and `service_account_key`. Please
    see the [Service Account documentation][sa-iam-docs] for more information.

`service_account_email` is listed first, however in fact only `service_account_key` is used, as email is pulled from the key (#8, #9).

**Expected behavior**

The documentation must clearly reflect that only `service_account_key` is needed for authentication, and also outline the specific circumstances when `service_account_email` should be used.

**Comment by sethvargo** [comment]
`service_account_email` is [used if given](https://github.com/GoogleCloudPlatform/github-actions/blob/20c294aabd5331f9f7b8a26e6075d41c31ce5e0d/setup-gcloud/src/setup-gcloud.ts#L118), but it defaults to the empty string because it can be inferred from _certain types_ of keys, specifically, the value is required when using the older format `.p12` keys.

Providing the service account email for JSON verifies the email matches the one in the key, which can be used as an extra sanity check.

**Comment by IlyaSemenov** [comment]
I am not sure which reply do you expect? Sure thing, I understand that service account email might be useful in certain circumstances, including the older key format.

It is however not needed in most *mainstream* operations:
* It is not used by the [sister GitHub action](https://github.com/actions-hub/gcloud).
* It is not needed in other similar flows such as [Google Cloud Getting Started](https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable).

so the current wording where `service_account_email` is unquestionably placed first is a bit misleading to my thinking. If you don't concur to that, just close the ticket.

(That was a friendly feedback from someone who just realised that one of his CI/CD secrets doesn't serve any purpose - other than the sanity check, indeed - and was happy to simplify the setup, nothing more.)

**Comment by sethvargo** [comment]
Thanks, opened https://github.com/GoogleCloudPlatform/github-actions/pull/96
